### ISSUE TITLE
Breadcrums are not generated for folders in IE11 

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#115]
(customization area file manager)
1. Open File Manager in IE11;
2. create some folder;
3. enter to the created folder;
4. pay attention on breadcrums at the bottom of page.
Result: breadcrums are not changed and display value "Customization area".

**Comment by kvolkovich-sc** [comment]
See https://github.com/OpusCapita/filemanager/issues/116
