### ISSUE TITLE
Impossible to do any actions in IE11 if enter to some folder

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#116]
(customization area file manager)
1. Open File Manager in IE11 browser;
2. create some folder;
3. enter to the created folder;
4. try to do any action (e.g. create, rename, download and ect.).
Result: impossible to do any action. Error appears in console browser:
SCRIPT5077: Cannot define property '$jscomp_hidden_27929855389119295': object is not extensible
Unhandled promise rejection TypeError: Cannot define property '$jscomp_hidden_27929855389119295': object is not extensible

**Comment by kvolkovich-sc** [comment]
See https://github.com/OpusCapita/filemanager/issues/117
