### ISSUE TITLE
Need an event when file or directory selected

### ISSUE THREAD

**Issue by m-hoseinzadeh** [OpusCapita/filemanager#135]
Is there anyway to add event to listview items in FileNavigator component?

**Comment by kvolkovich-sc** [comment]
Hi! In the current version, this possibility is not provided.
Sure, we can add `onSelectionChange` and `onResourceChange` events and publish a new version in a couple of days (rather, closer to this weekend).

Your question looks reasonable and we'll add more events later.

**Comment by kvolkovich-sc** [comment]
@m-hoseinzadeh
Take a look at an [example](http://opuscapita-filemanager-demo-add-events-135.azurewebsites.net/?currentComponentName=FileNavigator&maxContainerWidth=100%25&showSidebar=false) (wait a few seconds if it opens for a long time), read the new props documentation.

What do you think about it? Is it solves your issue?

**Comment by m-hoseinzadeh** [comment]
thanks,
demo is perfect!

**Comment by kvolkovich-sc** [comment]
Released in `v1.0.1`

Added FileNavigator props:

| Name                           | Type                    | Description                                                 |
| ------------------------------ | :---------------------- | ----------------------------------------------------------- |
| onResourceChange               | func                    | `resource => ...`                                           |
| onResourceChildrenChange       | func                    | `resourceChildren => ...`                                   |
| onResourceLocationChange       | func                    | `resourceLocation => ...`                                   |
| onSelectionChange              | func                    | `selection => ...`                                         |
