### ISSUE TITLE
Ability to set fsRoot sub-dir as client context dynamically with request

### ISSUE THREAD

**Issue by cstjohn-bhg** [OpusCapita/filemanager#140]
It would be useful and desirable to be able to supply a prop to FileNavigator that could be used to supply a "starting sub-directory" of the server's configured "fsRoot".  The FileNavigator would then work within this context as its base directory.

Example:
  - I have a fsRoot on the server of /var/config/
  - /var/config/ has sub-directories for a set of applications
  - Based on previous user input of desired application to configure, I want to render the FileNavigator in the /var/config/<application> context.

**Comment by kvolkovich-sc** [comment]
Hi!

Server config `fsRoot: "/var/config"`

FileNavigator1 `root: "/context1"` on client => `/var/config/context1` on server
FileNavigator2 `root: "/context2"` on client => `/var/config/context2` on server
FileNavigator3 `root: "/context3"` on client => `/var/config/context3` on server

Do I understand you right?

**Comment by cstjohn-bhg** [comment]
Hi Kirill!  Yes, that is precisely what I meant.  Is there a way to support this already that I have missed?

**Comment by kvolkovich-sc** [comment]
I think no.

But you can easily implement it by using Filemanager middleware and replacing `apiRoot` or `nodeV1` connector in client application runtime.

Something like this:

**server/index.js**

```js
const filemanagerMiddleware = require('@opuscapita/filemanager-server').middleware;

app.use(
  '/context1', 
  filemanagerMiddleware({ fsRoot: '/var/config/context1', rootName: 'Context1' })
);

app.use(
  '/context2', 
  filemanagerMiddleware({ fsRoot: '/var/config/context1', rootName: 'Context2' })
);

app.use(
  '/context3', 
  filemanagerMiddleware({ fsRoot: '/var/config/context1', rootName: 'Context3' })
);
```

> Note. In complex application I suggest to use `router.use` instead of `app.use`. See [details](http://expressjs.com/en/4x/api.html#router)

**client/Component.jsx**

```jsx
<FileNavigator
...
  apiOptions={{
    ..._scope.connectors.nodeV1.apiOptions,
      apiRoot: `http://<your_server_url>/<context_1_or_2_or_3>/api`
  }}
...
/>
```

**Comment by kvolkovich-sc** [comment]
@cstjohn-bhg can you please write a comment here if it works? Then I'll close this issue.

**Comment by cstjohn-bhg** [comment]
Yes, following this method worked out.  Thanks!

To circle back on _dynamic_ routes for anyone who stumbles across this, on the client component you'll need something similar to:
```
var connectorNodeV1 = require('@opuscapita/react-filemanager-connector-node-v1').default;

class ContextualFileManager extends React.Component {
  constructor(props) {
    super(props);
    this.apiOptions = Object.assign(
      connectorNodeV1.apiOptions,
      {
        apiRoot: '/filemanager/'+this.props.context+'/api'
      },
    );
  }
  
  render() {
    return(
      <FileManager>
        <FileNavigator
          id="filemanager-1"
          api={connectorNodeV1.api}
          apiOptions={this.apiOptions}
          capabilities={connectorNodeV1.capabilities}
          initialResourceId={'Lw'}
          listViewLayout={connectorNodeV1.listViewLayout}
          viewLayoutOptions={connectorNodeV1.viewLayoutOptions}
        />
      </FileManager>
    );
  }
}
```
And on the server:
```
  router.use(
    '/filemanager/:context/',
    (req,res) => {
      var fmm = filemanagerMiddleware(
        Object.assign(
          config,
          {
            fsRoot: currentDir(req.params.context),
            rootName: 'Context '+req.params.context
          }
        )
      );
      return fmm(req,res);
    }
  );

```

**Comment by kvolkovich-sc** [comment]
Thanks for the helpfull addition!)
