### ISSUE TITLE
How Send Custom Header In Client React-filemanager to Server ?

### ISSUE THREAD

**Issue by ParhamZare** [OpusCapita/filemanager#159]
Hi
How Send Custom Header in Request ?
like {Authorization: Bearer}

**Comment by kvolkovich-sc** [comment]
Hi, @ParhamZare.

We'll think about this issue. I not sure that [hardcode] some headers (https://github.com/OpusCapita/filemanager/pull/160) is the best solution.

At current time I propose you just fork `@opuscapita/react-filemanager-connector-node-v1`

**Comment by kvolkovich-sc** [comment]
Such behavior will be implemented in scope of this issue:

https://github.com/OpusCapita/filemanager/issues/224

**Comment by kvolkovich-sc** [comment]
See comment here. https://github.com/OpusCapita/filemanager/issues/257
