### ISSUE TITLE
try/catch with async/await

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/filemanager#168]
The following pattern is erroneous:

```javascript
async function f() {
  const response = await request().catch(err => {
    console.log(err);
  });
  const { items } = response.body;
  return items;
}
```

because in case of error, **response** is assigned **undefined** and execution flow continues to

```javascript
const { items } = response.body;
```

`try {...} catch (err) {...}` construct should be used with async/await, instead of `promise.catch()`.  In most cases **try/catch** should be places in upper-lever functions calling async functions.

See [Error Handling with async/await](https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9#8014) for details.

**Comment by amourzenkov-sc** [comment]
*All* async calls should also be error-proof by handling errors and exit/rollback code flow.

**Comment by estambakio-sc** [comment]
[Demo website](http://opuscapita-filemanager-demo-issue-168-refactor-async-await-e.azurewebsites.net/)

**Comment by nstoliar-sc** [comment]
1. Message about error is not displayed if user tries to download single file when disabled connection to network.
2. File manager is not opened in IE. Error 'SCRIPT1006: Expected ')'' appears in console of browser.
Comment from console:
"function getMessage(locale, key, params=null) {
  let translationExists = (translations[locale] && translations[locale][key]);
  let translation = translationExists ? translations[locale][key] : translations['en'][key];
  if (params === null) {
    return translation;
  }" 
Spent 2 hours.

**Comment by estambakio-sc** [comment]
@nstoliar-sc fixed, please check.

**Comment by nstoliar-sc** [comment]
Tested. Actions of file manager work correctly. Messages about wrong implementation of action while disconnecting to network appears correctly. Please, merge with master branch. Spent 2 hours.
