### ISSUE TITLE
Move onSuccess/onFail outside of async functions

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/filemanager#169]
Replace

```javascript
async function f(arg, { onStart, onSuccess, onFail, onProgress }) {
  ...
)
```

with

```javascript
async function f(arg) {
  ...
)
```

to prevent tight coupling of async function with **onStart/onSuccess/onFail/onProgress**.  These callbacks should be called outside of the function.

**Comment by estambakio-sc** [comment]
`onSuccess`, `onFail` moved outside api sunctions in #180

**Comment by abaliunov-sc** [comment]
Done
