### ISSUE TITLE
Pane of actions is not displayed for Filemanager in IE. 

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#190]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01

Pane of actions is not displayed for Filemanager in IE. 

![139](https://user-images.githubusercontent.com/25082017/37402322-30eabcd4-279c-11e8-9e23-76e2bb1a46be.png)

**Comment by stamkov-sc** [comment]
Doesn't reproduced anymore

**Comment by nstoliar-sc** [comment]
Not reproduced.
