### ISSUE TITLE
Message of deleting is not placed in deleting pop-up in IE

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#192]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01

Message of deleting is not placed in deleting pop-up in IE:

![140](https://user-images.githubusercontent.com/25082017/37402676-896ff8f0-279d-11e8-881f-b2a8fb60a0f0.png)

**Comment by stamkov-sc** [comment]
Doesn't reproduced anymore.

**Comment by nstoliar-sc** [comment]
Not reproduced.
