### ISSUE TITLE
Stream download of archived files

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/filemanager#194]
**What is the current behavior?**
Multiple files are downloaded in sequence and archived on client side by reading their content into memory -- which is problematic for large files.

**What is the expected behavior?**
*Server-nodejs* package allows downloading of multiple files/folders with in a zip-archive.  Implement this functionality.  The only limitation is that files/folders to download *must* be from the same parent dir.

**Comment by abaliunov-sc** [comment]
Done
