### ISSUE TITLE
 'Browse' button appears during file upload in IE 11

### ISSUE THREAD

**Issue by amogdalov-sc** [OpusCapita/filemanager#201]
![image](https://user-images.githubusercontent.com/25083028/38509827-b7c67baa-3c2b-11e8-802e-4ce1e266105f.png)

Current behavior:
 'Browse' button appears during file upload

 Step to reproduce:
1. Open filemanager in **IE 11**
2. Try to upload

This bug is reproduced in v1.0.7

**Comment by abaliunov-sc** [comment]
See [http://opuscapita-filemanager-demo-iisue-201-browse-button-bug.azurewebsites.net/?currentComponentName=FileManager&maxContainerWidth=100%25&showSidebar=false](http://opuscapita-filemanager-demo-iisue-201-browse-button-bug.azurewebsites.net/?currentComponentName=FileManager&maxContainerWidth=100%25&showSidebar=false)

Done.

**Comment by abaliunov-sc** [comment]
Done
