### ISSUE TITLE
[Feature Request] turning off the printing and customizes the url api

### ISSUE THREAD

**Issue by cjs840312** [OpusCapita/filemanager#209]
Thanks for the delicate file manager
I'm wondering if there's a way to **disable** all the printing message both **on server side and client side**?
It prints message on every request, which is a bit annoying.

And another issues is that, since it need to use it as a middle ware in my project, the request method and URI should not conflict to others (explicitly : /api/*).
What's the best approach to **customize this part,** since /api is a common name for routers, so I need to rename it properly

**Comment by kvolkovich-sc** [comment]
Hello, @cjs840312!

Please update all packages to version `1.1.0-beta.0`

- Cleaned up an odd `console log(...)` at client-side.
- Add possibility to pass "logger" as config parameter to server

Try:

```
// server config
{
  logger: {
    log: () => {},
    info: () => {},
    warn: () => {},
    error: () => {}
  }
}
```

- `/api` postfix for each API route has been removed. Now you can control it at your side.

Please try it and if everything works OK, I'll close this issue.

**Comment by cjs840312** [comment]
Thanks for cleaning up the console.log and modifying the server side so fast !
The server-logger and client-console seems working well.
But there still remain a little issue.
Now the `/api`  prefix has removed so it won't conflict with my code, however, for development concern,
It is still possible to conflict with other router.
So what I think the best way to handle this issue is to add a new option in th config 
such as  `{ customRoute : {download: "/api/download"}}`
Before you update the code, what I'm doing is overwriting the whole router (packages/filemanager-server/router/index), and modifying the URI.
I know it's bothering, but I hope we can make it better！

**Comment by kvolkovich-sc** [comment]
I think, it much simpler to place filemanager root route somewhere to `/your/filemanager/route`:

```
/your/filemanager/route/files
/your/filemanager/route/download
/your/filemanager/route/etc
```

If you want, you still want it, you can fork this repo and make your implementation and send me a link or make a pull request.

**Comment by cjs840312** [comment]
Oh!! My bad .   I totally forgot that!
That's absolutely more elegant and efficient !
Thank you very much.
I'll try those functionality tomorrow. And you can close this issue if no other problem!

**Comment by kvolkovich-sc** [comment]
Yes, Filemanager is simply a wrapper and there is several reasons for this.
