### ISSUE TITLE
Update "superagent" and "lodash" dependency to fix potential vulnerability

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/filemanager#217]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | 0.5h
Remaining Estimation | 0.5h

![screen shot 2018-08-15 at 3 03 06 pm](https://user-images.githubusercontent.com/24652543/44147332-5a4b34ae-a09c-11e8-8542-f8389681bc7c.png)

Don't forget do it across all lerna packages.

**Comment by stamkov-sc** [comment]
Updated.
