### ISSUE TITLE
How to install the forked scoped package? 

### ISSUE THREAD

**Issue by Mengsuper** [OpusCapita/filemanager#218]
I have a very naive question about how to install the package dependency from the forked repo. 
I'm planing to make some changes on connector-node-v1 for my own project. I forked the whole repo, and try to install the package via 
npm install https://github.com/[myGitHubName]/filemanager.git#[myNewBranchName]. 

However, there is an error: "Missing package version". It seems that the package.json doesn't have a version attribute. Could anyone know how to solve this? Thank you very much in advance.

**Comment by kvolkovich-sc** [comment]
@Mengsuper, as I understand, the problem isn't about "scoped" package.

Its more about [multi-package repository](https://github.com/lerna/lerna). So, you need possibility to install specific package from subdir. 

I think its no possible for now.

https://github.com/npm/npm/issues/2974

You can publish your package to npmjs.org and install it in a common for manner npm.

**Comment by Mengsuper** [comment]
@kvolkovich-sc  Thanks for the reply, really appreciate it. I have published my package to npm.
