### ISSUE TITLE
Node Connector V1 recursive queries to the API

### ISSUE THREAD

**Issue by worldbeater** [OpusCapita/filemanager#228]
Hi! I've played around a bit with a local FileManager demo recently and noticed that when I use **connector-node-v1** API provider and open, say, a `folder1/folder2/folder3/folder4/folder5` path, I get 5 (five!) GET requests sent to the server. I tried to find out what is causing this <a href="https://github.com/OpusCapita/filemanager/blob/master/packages/connector-node-v1/src/api.js#L43">and succeeded</a>. 

```js
async function getParentsForId(options, id, result = []) {
  if (!id) {
    return result;
  }

  const resource = await getResourceById(options, id);
  if (!resource) {
    return result;
  }

  const parentId = resource.parentId;
  if (!parentId) {
    return result;
  }

  const parent = await getResourceById(options, parentId);
  return getParentsForId(options, resource.parentId, [parent, ...result]);
}
```

The code recursively calls `getResourceById` method and that's not quite optimal. The deeper you dive into your file system, the bigger request count number you get. While Node API returns `ancestors` field <a href="https://github.com/OpusCapita/filemanager/blob/master/packages/server-nodejs/router/lib.js#L177">by default</a>, I think something similar to this snippet would be better:

```js
async function(options, id, result = []) {
  const route = `${options.apiRoot}/files/${id}`;
  const response = await request('GET', route);
  const resource = response.body;
  if (resource && resource.ancestors) {
    return resource.ancestors;
  }
  return [];
}
```

Perhaps, you might want to add a call to `normalizeResource` method exported from <a href="https://github.com/OpusCapita/filemanager/blob/master/packages/connector-node-v1/src/utils/common.js#L1">utils</a>. I can pull-request with these changes if you'd like me to. Thanks in advance!

**Comment by kvolkovich-sc** [comment]
Hello, @worldbeater!

Yes, there is a lot of redundant API calls too.
 
We did it for **connector-node-v1** when **server-nodejs** yet did't provide `ancestors` field in response.

You can make a PR.

If it will work as expected, well merge and release it. :rocket:

**Comment by kvolkovich-sc** [comment]
Also I don't see `ancestors` it in [API docs](https://opuscapita-mk8s-cluster-1.westeurope.cloudapp.azure.com/filemanager/master/api/docs/#files__id__get
).

If it works, but not documented, it should be added to documentation too.

**Comment by amourzenkov-sc** [comment]
[API docs](https://opuscapita-mk8s-cluster-1.westeurope.cloudapp.azure.com/filemanager/master/api/docs/#files__id__get
) are updated.
