### ISSUE TITLE
Demo server not working?

### ISSUE THREAD

**Issue by nkkollaw** [OpusCapita/filemanager#241]
Hi, I was trying to check out the project, but the demo server seems to be down?

**Comment by kvolkovich-sc** [comment]
Yes. You are right. We'll fix it at this week.

**Comment by kvolkovich-sc** [comment]
Fixed.

https://demo.core.dev.opuscapita.com/filemanager/master

**Comment by nkkollaw** [comment]
Ohhh... Very nice! Thanks.
