### ISSUE TITLE
Adding button to the tool bars

### ISSUE THREAD

**Issue by toddgeist** [OpusCapita/filemanager#244]
Is there a way to add custom buttons to the toolbar?

Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | ???h
Remaining Estimation | ???h

**Comment by kvolkovich-sc** [comment]
You can add it as new `capability` in `toolbar` context.

Example (sorry for formatting):

```jsx
let newCapabilityHandler = () => console.log('click');

let newCapability = {
    id: 'my-custom-button',
    icon: { svg: 'hello' },
    label: 'My Custom Button',
    shouldBeAvailable: () => true,
    availableInContexts: ['toolbar'],
    handler: newCapabilityHandler
  };
 
<FileNavigator
...
  capabilities={{
  ...connectorNodeV1.capabilities,
  newCapability
}}
/>
```

I think it should be enough. If not, you can provide some use case and we'll try to solve this issue together.

**Comment by toddgeist** [comment]
wow this looks nice. :-)

**Comment by kvolkovich-sc** [comment]
Tried code above) Sorry, its not working. Please wait for solution ~30m

**Comment by kvolkovich-sc** [comment]
I have added example (black bold circle).

![screen shot 2018-12-14 at 12 48 39 pm](https://user-images.githubusercontent.com/24652543/49995927-a2708980-ff9e-11e8-9b86-498c82211f61.png)

```jsx
capabilities={(apiOptions, actions) => ([
        ...(window.connectors.nodeV1.capabilities(apiOptions, actions)),
        ({
          id: 'custom-button',
          icon: {
            svg: '<svg viewBox="0 0 120 120" version="1.1"><circle cx="60" cy="60" r="50"></circle></svg>'
          },
          label: 'Custom Button',
          shouldBeAvailable: () => true,
          availableInContexts: ['toolbar'],
          handler: () => alert('Custom button click')
        })
      ])}
```


https://demo.core.dev.opuscapita.com/filemanager/master/?currentComponentName=FileNavigator&maxContainerWidth=100%25&showSidebar=true

**Comment by toddgeist** [comment]
that worked !  Thank you!
