### ISSUE TITLE
React Getting 404 for files directory 

### ISSUE THREAD

**Issue by EFXPROMedia** [OpusCapita/filemanager#246]
I am trying the FileManager 1.1.0-beta.4 with a React app but so far I have been unable to connect it to any of my APIs running with Node and Express.

if I try the apiRoot at localhost:3000 (React) it returns:

`http://localhost:3000/files/undefined/children?orderBy=name&orderDirection=ASC 404 (Not Found)`

if I try running it from React getting the root directory of My Node Server on port 3001 and it also returns an error:

`GET http://localhost:3001/files/ 404 (Not Found)`

maybe I am missing something silly but important or the documentation is not covering the full implementation necessary.

My Code:

```
import React, { Component } from 'react';
import { FileManager, FileNavigator } from '@opuscapita/react-filemanager';
import connectorNodeV1 from '@opuscapita/react-filemanager-connector-node-v1';

const apiOptions = {
  ...connectorNodeV1.apiOptions,
  apiRoot: `http://localhost:3001` // Or you local Server Node V1 installation.
}

class FileManagement extends Component{
  render(){

    const fileManager =  (
      <div style={{ height: '480px' }}>
         <FileManager>
           <FileNavigator
             id="filemanager-1"
             api={connectorNodeV1.api}
             apiOptions={apiOptions}
             capabilities={connectorNodeV1.capabilities}
             listViewLayout={connectorNodeV1.listViewLayout}
             viewLayoutOptions={connectorNodeV1.viewLayoutOptions}
           />
         </FileManager>
       </div>
     );

    return(
      <div>
        {fileManager}
      </div>
    )
  }
}

export default FileManagement;
```

Thanks

**Comment by kvolkovich-sc** [comment]
Looks like something wrong with your `express` setup.

This minimal config works for me.

```js
const express = require('express');
const path = require('path');

const filemanagerMiddleware = require('@opuscapita/filemanager-server').middleware;
const app = express();

const config = {
  fsRoot: path.resolve(__dirname, '/tmp'),
  rootName: 'Temp'
};

app.use('/filemanager', filemanagerMiddleware(config));

app.listen('3001', 'localhost');
```

![fm-screenshot](https://user-images.githubusercontent.com/24652543/50116867-71bd7800-025c-11e9-8727-a35517bd7dd0.png)

I it don't help, please share your server code.

**Comment by EFXPROMedia** [comment]
It works now, but I would consider making the documentation clearer for some of us.

The 2 things that prevented me from getting it right was the middleware requirement to be installed in the Express server and the React apiOptions.

So to clarify an easier understanding if this occurs again:

1. Configure first your Express server (just like you mentioned above) but the path would that best fit for React I imagine using would be:

```
const config = {
  fsRoot: path.resolve(__dirname, './react-server/build/files'),
  rootName: 'Files'
};
app.use('/filemanager', filemanagerMiddleware(config));
```

This way you can call files that have been uploaded there before from other upload methods, however, that's my interpretation of the scenario I caused, the folder might be anywhere in your React or server directory. 

2. From your React Component, you call:

```
const apiOptions = {
  ...connectorNodeV1.apiOptions,
  apiRoot: 'http://localhost:3001/filemanager' // this url has to match your express middleware url /filemanager
}
```
I can confirm its all working and its great! thanks!
