### ISSUE TITLE
Get file path

### ISSUE THREAD

**Issue by EFXPROMedia** [OpusCapita/filemanager#247]
Is there any control available to get the selected file path or preview?

It would be nice to be able to click on a file and assign buttons in the file row of the table, so we can assign custom actions to files e.g preview or get file path.

**Comment by kvolkovich-sc** [comment]
How to get file path.

See docs at this page. https://demo.core.dev.opuscapita.com/filemanager/master/?currentComponentName=FileNavigator&maxContainerWidth=100%25&showSidebar=false


You can get `rowData` using `onResourceItemClick`.

There is `ancestors` array in `rowData` where each item has `name` field.

You can concat it to get file path (relative to server-side `fsRoot`).
