### ISSUE TITLE
Windows - Error: Invalid path, it must start with "\\"

### ISSUE THREAD

**Issue by toddgeist** [OpusCapita/filemanager#251]
This line
https://github.com/OpusCapita/filemanager/blob/76731fd7d96ecae8d9233ae743415fc7656f2783/packages/server-nodejs/router/lib.js#L111-L113

Throws an error if you pass a full file path on windows with a drive letter.  Is there a reason why you can't pass the path with a leading drive letter? Or is this just a bug

I need to be able to target folders that might be on other drives.

Todd

**Comment by kvolkovich-sc** [comment]
I think its a bug. I'll clarify it tomorrow.

**Comment by amourzenkov-sc** [comment]
It is a bug indeed. I'll fix it ASAP.

**Comment by amourzenkov-sc** [comment]
@toddgeist Do you want to access files outside [config.fsRoot](https://github.com/OpusCapita/filemanager#basic-usage) ? Current implementation does not allow it for security reasons. As a workaround, Linux has soft/hard links. I am unaware of any Windows solutions.

`id2path` function decodes `id` to a path relative to **config.fsRoot**. See [documentation](https://github.com/OpusCapita/filemanager/blob/master/packages/server-nodejs/docs/api-overview.md#general-considerations) for details.  Being relative, the path *never* start with a letter, but _always_ with a slash.

**Comment by toddgeist** [comment]
I want to access files inside of config.fsRoot

I am setting config.fsRoot to a path. That path leads with a drive letter. When I do that, I get the error.

Does that help?

**Comment by amourzenkov-sc** [comment]
@toddgeist I'll try to reproduce it in Windows. What operation/API call it fails on?

**Comment by toddgeist** [comment]
The initial load fails. The react view never loads.

**Comment by amourzenkov-sc** [comment]
@toddgeist Sorry, I could not reproduce the error. My config:

```
{
	fsRoot: 'C:',
	rootName: 'Customization area',
	readOnly: false,
	port: process.env.PORT || '3020',
	host: process.env.HOST || 'localhost'
}
```
then I run `npm start` from **filemanager/packages/server-nodejs** folder. In another terminal I run

```
curl http://localhost:3020/files
```

and then

```
curl http://localhost:3020/files/XA/children
```

Everything goes flawlessly.

**Comment by toddgeist** [comment]
I'll see if I can get simple repo that shows the problem

**Comment by toddgeist** [comment]
Sorry  - I think I tracked this down. It is likely coming from this:
```
<FileNavigator
   ...
   initialResourceId={"Lw"}
   ...
/>
```
I just copied and pasted the intitialResourceId from the docs. I didn't realize that "Lw" was for macs and you would need "XA" for use with window servers.

I am going to go confirm this.  I'll respond with my results.

**Comment by toddgeist** [comment]
This was the problem.  The resolution was to NOT set `initialResourceId` at all.

Thank you for your help :-)
