### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by magpielover** [OpusCapita/filemanager#253]
Hello,
I'm trying to use the project in my personal React application. I use filemanagermiddleware and the node connector. However, in my first attempt I got the following error. It might not look very descriptive but seems to be a package/version error. Any idea?
> ReferenceError: self is not defined
>     at /Users/ugur/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:442:30
>     at /Users/ugur/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:437:47

**Comment by kvolkovich-sc** [comment]
Hello, @magpielover. Maybe you can share your project?

There is no way to determine the error reason by current information.

**Comment by magpielover** [comment]
Hi,
The project is comprised of a React UI, redux for data management and SSR with Next.js, I have a very light server.js file in the root level where I declare my routes and configs. I created a FileManager component with your "Client React" package in the frontend and followed your guide for creating a middleware. However, when I "npm run", browser displays the error 

> ReferenceError: self is not defined
>     at /Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:442:30
>     at /Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:437:47
>     at module.exports (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:459:68)
>     at Object.<anonymous> (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:32219:36)
>     at __webpack_require__ (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:30:30)
>     at Object.defineProperty.value (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:11973:1)
>     at __webpack_require__ (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:30:30)
>     at Object.defineProperty.value (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:12907:19)
>     at __webpack_require__ (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:30:30)
>     at Object.<anonymous> (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:10502:18)
>     at __webpack_require__ (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:30:30)
>     at Object.<anonymous> (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:32662:18)
>     at __webpack_require__ (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:30:30)
>     at /Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:76:18
>     at /Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:79:10
>     at webpackUniversalModuleDefinition (/Users/Desktop/with-redux-wrapper-app/node_modules/@opuscapita/react-filemanager/lib/index.js:3:20)

so not sure what I can tell more about the app

**Comment by kvolkovich-sc** [comment]
OK. I'll try to reproduce it with `with-redux-wrapper-app`.
Not right now, but in closest 24 hours :)

**Comment by kvolkovich-sc** [comment]
Sorry, but I can't reproduce the error.

I'll can't help you if you'll not share a repository to `npm install && npm start`

**Comment by magpielover** [comment]
Actually found a hack, I import the module in `componentDidMount` so it renders in the client side. But thank you for your time.

**Comment by kvolkovich-sc** [comment]
OK, no problems.

**Comment by theZulqarnain** [comment]
> Actually found a hack, I import the module in `componentDidMount` so it renders in the client side. But thank you for your time.

Can you please share ur code,**How did you resolve this issue on Nextjs.**
Thanks
