### ISSUE TITLE
Not an Issue..

### ISSUE THREAD

**Issue by jmandivarapu1** [OpusCapita/filemanager#255]
Hi Team,

I just want to know can I use this package after fetching my files from s3. 
Like can I just my files like json to get that listview. If so can I get any such example i checked all but didn't find one for this usecase.

Regards,
Jay

**Comment by kvolkovich-sc** [comment]
Hi. Sorry for a long reply.

I don't think that we have a plan to implement this feature by our effort in the near future.

But PRs always are welcome.
