### ISSUE TITLE
Document API object

### ISSUE THREAD

**Issue by kamiljano** [OpusCapita/filemanager#256]
I have a custom backend and I would love to build a custom api object to communicate with it. At this point the only thing that can be done in that regard is reverse-engineering this: https://github.com/OpusCapita/filemanager/blob/master/packages/connector-google-drive-v2/src/api.js

Later on I will also need to be able to use the component to browse the local files (it's a desktop node.js app) what will require me to implement yet another api.

The component shouldn't make the assumption that the data is pulled from a server. Instead it should be able to pull any API component that is passed to it. This means that the necessity of specifying the apiOptions.apiRoot is also a weird idea

**Comment by kvolkovich-sc** [comment]
Hi @kamiljano!

Agreed with your thoughts. Do you have time to make PR?

If no, I can't promise that it will be fixed soon. PR is the fasted way to achieve what you want.

**Comment by kamiljano** [comment]
Heh... I was hoping for the docs, because I didn't want to spend time figuring this thing myself :P
I'll see how desperate I become about it :P
