### ISSUE TITLE
Add Header value to API call

### ISSUE THREAD

**Issue by marktoh** [OpusCapita/filemanager#257]
I have an access token that I would like to pass as a key:value pair like `Authorization: Bearer {accessToken}` into the header of the HTTP Request for authentication.

Is there a way for me to modify the configuration options of the API call? I have looked into `apiOptions` but I am having some trouble locating the props that it receives.

**Comment by kvolkovich-sc** [comment]
Hi!

There is no support for this functionality now.

The easiest way to achieve what you want - just run a simple proxy to modify headers as you wish.

For example: https://serverfault.com/questions/391554/forward-custom-header-from-nginx-reverse-proxy
