### ISSUE TITLE
Will this work with Angular ?

### ISSUE THREAD

**Issue by khoiminhpham** [OpusCapita/filemanager#280]
Just a quick question, I can see how it works on React client and node.js server, anyone knows if this will work on Angular 8 client and node.js server as well ?

Thanks,

**Comment by visortelle** [comment]
First search result in Google by "react component in angular": https://github.com/microsoft/angular-react

**Comment by khoiminhpham** [comment]
Can't you guys just make one for angular 2+ :(

**Comment by visortelle** [comment]
> Can't you guys just make one for angular 2+ :(

Yeah. We can do everything. 🤣

Maybe it really has the sense to make wrappers for:

- Angular
- Vue
- Vanilla JS

It shouldn't be too complex. If anyone would do a PR, it would be great.
