### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/filemanager#29]
- [x] Implement `locale` property for `FileManager` and `FileNavigator` components. Take a look at a similar [example](https://github.com/OpusCapita/react-dates/blob/master/src/client/components/translations.js#L1)

- [x] Create a file **translations.js** for **connector-node-v1** and **connector-google-drive-v2**. If we'll have a lot of translations, we'll split these files to the separate files (per locale).

- [x] Add `locale` property to the `FileNavigator` documentation file with a link to the file with available translations for each of connectors.

Please **don't** use https://github.com/OpusCapita/i18n

**Comment by apechenko-sc** [comment]
I disagree this is a low prio issue. This is rather critical and can be also treated as a bug.

**Comment by kvolkovich-sc** [comment]
@apechenko-sc it had "low priority" for us when we implemented base Filemanager functionality.

**Comment by kvolkovich-sc** [comment]
Done.

**Comment by kvolkovich-sc** [comment]
Column names are not translated properly. @abaliunov-sc, can you take a look?

**Comment by kvolkovich-sc** [comment]
`en` and `de` locales added.

@nstoliar-sc, please test it.

[Demo](http://opuscapita-filemanager-demo-issue-29-locale-update-fix.azurewebsites.net/?currentComponentName=FileManager&maxContainerWidth=100%25&showSidebar=false)

**Comment by nstoliar-sc** [comment]
'Cancel' in pop-ups with actions 'Create folder' and 'Rename' hasn't German translation. Spent 0.5 hour.

**Comment by kvolkovich-sc** [comment]
Fixed
