### ISSUE TITLE
How to use an independent component in Client React Package alone? For example: LocationBar, ListView?

### ISSUE THREAD

**Issue by Gzbox** [OpusCapita/filemanager#291]
How to use an independent component in Client React Package alone? For example: LocationBar, ListView?
I don't know how to import from'@opuscapita/react-filemanager'

Urgently want to know the answer, thank you

@kvolkovich-sc @visortelle

**Comment by visortelle** [comment]
The components you listed are not exported. If you want, please modify this file and make a pull request.

https://github.com/OpusCapita/filemanager/blob/master/packages/client-react/src/client/index.js
