### ISSUE TITLE
Implement basic server with node.js (list folder content, download/upload/delete file, create/delete folder)

### ISSUE THREAD

**Issue by amourzenkov-sc** [OpusCapita/filemanager#3]
Fabric version should include:
- get file(s) list
- download file(s)
- upload(create) files(s) / create folder
- delete file(s)

**Comment by amourzenkov-sc** [comment]
добавить флаги canRename и canCopy в список capabilities

**Comment by kvolkovich-sc** [comment]
Implemented.

**Further work will be on separated branches.**
