### ISSUE TITLE
Translate message "Nothing to show"

### ISSUE THREAD

**Issue by MaximeMazet** [OpusCapita/filemanager#305]
I made a pull request to translate the message into french and accept react 17

**Comment by estambakio-sc** [comment]
Implemented in #319, released as [1.1.10](https://github.com/OpusCapita/filemanager/releases/tag/v1.1.10)

**Comment by achernyakevich-sc** [comment]
Internationalization for this UI part added. As well it include translations for FR, DE, Ru locales.

Messages in other languages will be added later. Or you could create a pull-requests - it will be welcome! :)
