### ISSUE TITLE
Project is not maintained. ⚠️

### ISSUE THREAD

**Issue by visortelle** [OpusCapita/filemanager#307]
For PR and issue creators.

As I know, the project is not maintained anymore.

There is very small chance that your PR will be merged.

I’ll continue to answer the questions about existing functionality, but don’t have a hope about new functionality or bugfixes.

Also I have plans to reimplement the filemanager.

Stay tuned. 🚀

**Comment by achernyakevich-sc** [comment]
> For PR and issue creators.
> 
> As I know, the project is not maintained anymore.

This is not completely true. :)

But really owner of this repository has lowered down priority of this kind development so it could cause some delays in reviewing PRs and publishing fixes. But me and my team will try to pay attention and help to move it forward. :)

P.S. Though maybe it really could be a good idea to implement new one that will avoid some mistakes made during designing of this one.
