### ISSUE TITLE
Can't upload files, but can delete when used with oauth2-proxy reverse proxy.  

### ISSUE THREAD

**Issue by raj-katonic** [OpusCapita/filemanager#320]
![issue](https://user-images.githubusercontent.com/81794052/126747648-7492cbe6-6ea9-4ef9-82ef-dc258ac1f75d.png)

File uploading process does start on bottom right when I try to upload, it does'nt
upload. Delete operation runs fine.
What must be the issue here ? 

Thanks

**Comment by achernyakevich-sc** [comment]
@raj-katonic 

My experience said me that problem could be related not to the component itself, but to the infra configuration. I would recommend you to turn off reverse proxy and check. If upload will work successfully then the most probably you need to check configuration of your reverse proxy for permissions to upload files and the size limitation for files you upload.

Please, could you test the proposed scenario and provide us feedback. We either will try to dig the issue deeper or close it.

> File uploading process does start on bottom right when I try to upload, it does'nt
> upload. Delete operation runs fine.
> What must be the issue here ?
> 
> Thanks

**Comment by visortelle** [comment]
@raj-katonic, try to upload an empty or any less than 4KB file.
If this operation will be finished successfully, then try to check something like `max_body_size` configuration property of the ingress proxy you use in front of oauth2-proxy.

**Comment by raj-katonic** [comment]
Thanks @visortelle  and @achernyakevich-sc for replying, I tried uploading empty file still it is not getting uploaded. The upload process does start and complete on the right bottom but doesn't do the work. 
And yeah when I remove the reverse proxy it works fine. But still I have my other applications which run fine to upload files on them when used behind reverse proxy.
Thanks :)

**Comment by achernyakevich-sc** [comment]
@raj-katonic 
> And yeah when I remove the reverse proxy it works fine. But still I have my other applications which run fine to upload files on them when used behind reverse proxy with same configuration.

It just let us think that reverse proxy configuration for this particular application looks as a source of problem. You could try to compare reverse proxy configs of working and not working application.

Meantime, it would be great if you will give us feedback as soon as you will have found reason of the problem. So we will be sure it is not component specific or it is really a bug. I will place this issue to hold for one month. If there will be no confirmation from you we will close this issue as _not reproducible_.

Thank you.

With best regards and wishes,
Alex.

**Comment by visortelle** [comment]
@raj-katonic, did you try to check if the HTTP request headers list differs in the cases when oauth-proxy is enabled and disabled for the upload request?
You can try to check it both in the browser dev tools and in the filemanager's server logs.

**Comment by estambakio-sc** [comment]
Makes sense to look into 
- ingress logs 
- oauth2-proxy logs 
Right when you initiate upload.

**Comment by raj-katonic** [comment]
@visortelle  and @estambakio-sc here are the logs of both containers when I try to upload file (starting below "------------" in images).
1. oauth2-con container
![logs-oauth2](https://user-images.githubusercontent.com/81794052/127186758-23092a53-b411-4354-9b95-29850bc26f76.png)


2. filemanager container 
![logs-file-manger-container](https://user-images.githubusercontent.com/81794052/127186575-69c93a3d-bdb0-4201-8f0a-f4e05fa2e0c1.png)

I guess this should help.

I tried using this filebrowser [hurlenko's filebrowser](https://hub.docker.com/r/hurlenko/filebrowser), and it is working fine with the same configuration. 

Thanks :)

**Comment by visortelle** [comment]
@raj-katonic, will you try to fix this issue or will just use the hurlenko's filebrowser?
  
If this issue isn't relevant to you anymore, I think you can close it. :)

**Comment by raj-katonic** [comment]
Sure I'm closing it thanks for replying everyone :)
