### ISSUE TITLE
There's no Drive Connector Docs.

### ISSUE THREAD

**Issue by stylessh** [OpusCapita/filemanager#325]
I can't find any example or documentation to successfully connect google drive to the file manager!

Can get some help?

**Comment by visortelle** [comment]
At first, you should get `client_id` and `api_key` to get access to Google Drive API. See https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid

Then see the second instance of the `FileNavigator` component.

**Comment by stylessh** [comment]
Thanks! 
What about the window.googleSignIn function?

**Comment by visortelle** [comment]
What 

> Thanks! What about the window.googleSignIn function?

What about it?

1.

https://github.com/OpusCapita/filemanager/search?q=googleDriveSignIn

2.

https://github.com/OpusCapita/filemanager/blob/5413e279b24e165f0920cac317ee9459f0b20ced/packages/client-react/src/client/components/FileManager/FileManager.SCOPE.react.js#L49

**Comment by stylessh** [comment]
Thanks a lot, mate. Got it working!
