### ISSUE TITLE
Online demo doesn't work

### ISSUE THREAD

**Issue by visortelle** [OpusCapita/filemanager#330]
Is it broken or the deployment just sleeps 😴 because it's Sunday today?

**Comment by achernyakevich-sc** [comment]
@estambakio-sc Please, could you check when will have some free time. :)

**Comment by visortelle** [comment]
It's back online! Thank you. 🙂

**Comment by estambakio-sc** [comment]
> It's back online! Thank you. 🙂

Yeah it was temporarily down, now should be back online :)
