### ISSUE TITLE
Update prop-types library to version 15.6.2+ to fix high vulnerability in used under the hood node-fetch package

### ISSUE THREAD

**Issue by UncleJart** [OpusCapita/filemanager#332]
Can you please update dependency in @opuscapita/react-filemanager for prop-types library from version "15.6.0" to "15.6.2" or higher?
There is high level vulnerability in "node-fetch" package which is used under the hood - [node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor](https://github.com/advisories/GHSA-r683-j2x4-v87g) which is fixed in v.15.6.2 by [removing the fbjs dependency by inlining some helpers from it](https://github.com/facebook/prop-types/blob/main/CHANGELOG.md#1562).
Update from 15.6.0 to 15.6.2 should not break anything as according to release notes except mentioned above update, [only fix for an issue where outdated BSD license headers were still present in the published bundle](https://github.com/facebook/prop-types/blob/main/CHANGELOG.md#1561) was added. Probably it is also possible to update to latest prop-types lib version without any issues.

NPM audit review for @opuscapita/react-filemanager 1.1.11:
![2022-04-06_17h43_39](https://user-images.githubusercontent.com/15914509/162006614-bd51594a-476b-4ade-9b13-1140617439f9.png)
NPM audit review for prop-types 15.6.0:
![2022-04-06_17h45_38](https://user-images.githubusercontent.com/15914509/162006678-3be85e4c-298e-4a2a-b87b-d037acfaea99.png)
NPM audit review for prop-types 15.6.2:
![2022-04-06_17h46_46](https://user-images.githubusercontent.com/15914509/162006727-b2efef26-5736-424c-a253-16d225150e5e.png)

**Comment by estambakio-sc** [comment]
@UncleJart thank you, I'll have a look.

**Comment by estambakio-sc** [comment]
Released in https://github.com/OpusCapita/filemanager/releases/tag/v1.1.12
