### ISSUE TITLE
It is possible to upload two and more files with same names (google.drive)

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#61]
1. Open file manager;
2. highlight some file right mouse click;
3. click on 'Upload' item in pop menu;
4. select some single file on computer;
5. reload page;
6. highlight some file right mouse click;
7. click on 'Upload' item in pop menu;
8. select same file which was uploaded;
9. reload page with file manager.
Result: two files wit same names are displayed in file manager.
Expected result: validation message about existing file with same name in current folder appears or uploaded file has changed name (for example numberic index is added in right part of file name).

**Comment by nstoliar-sc** [comment]
![66](https://user-images.githubusercontent.com/25082017/32667920-397258ae-c64d-11e7-9438-5b02659c30f6.png)

**Comment by asergeev-sc** [comment]
It is a feature of Google Drive.
