### ISSUE TITLE
Context menu is broken after downloading file in IE (node.js v.1)

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#85]
1. Open File Manager for node.js v.1 in IE 11;
2. highlight some file and open context menu by clicking right mouse;
3. download highlighted file;
4. try to open context menu again for any file or folder.
Result: context menu is not opened. Same situation appears exists if file is downloaded by clicking on appropriate button on tool pane.

**Comment by estambakio-sc** [comment]
I can't reproduce this bug.

**Comment by kvolkovich-sc** [comment]
Fixed: https://github.com/OpusCapita/filemanager/pull/99

**Comment by nstoliar-sc** [comment]
Tested.
