### ISSUE TITLE
Strange direction of arrows for sorting folder content

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#87]
![68](https://user-images.githubusercontent.com/25082017/32849542-7655c4f8-ca40-11e7-97e1-1f3f0575b65c.png)

If we see google.drive documents we will see follow situation: if arrow directed to upside, list is sorted ascending; if arrow directed to downside, list is sorted descending. But on current version of file manager arrows has reverse direction.

**Comment by kvolkovich-sc** [comment]
Fixed: https://github.com/OpusCapita/filemanager/pull/92

**Comment by nstoliar-sc** [comment]
Tested.
