### ISSUE TITLE
Context menu climbs on location bar

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#88]
![69](https://user-images.githubusercontent.com/25082017/32849880-83512caa-ca41-11e7-9290-ff1d5e81d95a.png)

1. Open File Manager for node.js v.1 in Firefox;
2. highlight third file from below and open context menu by clicking right mouse.
Result: context menu climbs on location bar.

**Comment by kvolkovich-sc** [comment]
Fixed: https://github.com/OpusCapita/filemanager/pull/94

**Comment by kvolkovich-sc** [comment]
Additional fixes: https://github.com/OpusCapita/filemanager/commit/eb8b119c92f203e6e3b376af610aedadd951f6cc

**Comment by nstoliar-sc** [comment]
Tested.
