### ISSUE TITLE
Message about uploading file with same name doesn't appear

### ISSUE THREAD

**Issue by nstoliar-sc** [OpusCapita/filemanager#89]
1. Open File Manager for node.js v.1;
2. upload some file;
3. upload same file again.
Result: uploaded file removes old file without any messaged. 
Expected result: message about existence of name of uploaded file in folder appears. User is invited to create file with other name or removing old one.

**Comment by kvolkovich-sc** [comment]
Fixed by creating a file with the same name + unique suffix (not show any message).

**Example:**

Existing files in folder:

* book.xls
* sheet.xls

Upload file with name *book.xls*

Result files in foder:

* book.xls
* book (1).xls
* sheet.xls

**Comment by nstoliar-sc** [comment]
Tested.
