### ISSUE TITLE
Do not download through npm

### ISSUE THREAD

**Issue by tyuexingzhe** [OpusCapita/filemanager#98]
Hello friends,
"npm install -E @opuscapita/react-filemanager " is empty.
I really like your project,I want to use one of the interfaces, but can not download, is there any other way to use your project?

**Comment by kvolkovich-sc** [comment]
Hi @tyuexingzhe It not released yet.

You can see progress [here](https://github.com/OpusCapita/filemanager/milestone/1)

We plan to complete the last steps and publish first version to npm today!

**Comment by tyuexingzhe** [comment]
Awesome!!!Very looking forward to your first version.

**Comment by tyuexingzhe** [comment]
Hello,friends
   1、I noticed you the first version, but I do not know how to use, are there some simple examples?
   2、In the Source Code have "node_v1" this interface, I can create  or delete a file, but how do I use it in the distribution?

**Comment by kvolkovich-sc** [comment]
I have add a basic usage examples to [README](https://github.com/OpusCapita/filemanager).

**Comment by tyuexingzhe** [comment]
so cool!~I have already started using it，and secondary development
